version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./novelspoint
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/novelspoint
    depends_on:
      - mongo

  frontend:
    build:
      context: ./novelspoint_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
